### ISSUE TITLE
Artifact stat reader bug

### ISSUE THREAD

**Issue by eyu8** [D1firehail/AdeptiScanner-GI#1]
The Crit dmg is not read properly.

![image](https://user-images.githubusercontent.com/32378135/144768232-e27ddbc9-78ab-4e86-ba64-166c02f798fa.png)

**Comment by D1firehail** [comment]
Looks like I'm only generating substat possibilities for up to 5 rolls of a stat, meaning it doesn't know about rolls only achievable with 4 stat start and all upgrades going into that one. I should have it fixed and a new release uploaded tomorrow unless something else comes up

**Comment by D1firehail** [comment]
Fixed in V1.0.1 https://github.com/D1firehail/AdeptiScanner-GI/releases/tag/V1.0.1
