### ISSUE TITLE
Failed to find artifact area

### ISSUE THREAD

**Issue by yoonbin9300** [D1firehail/AdeptiScanner-GI#10]
I have been trying to scan different artifacts but the scanner still does not work. I have set the screen to 1600x900 and made sure nothing else overlapped the game. I don't know what to do?

![Screenshot (2)](https://user-images.githubusercontent.com/119881267/205692632-7f67ff42-321f-43e8-824e-1cb0e3199960.png)

**Comment by D1firehail** [comment]
Basically, move to a different location (so you have a different blurry background), and try again *with a 5 star aritfact selected*.

Beyond not being a 5 star artifact, it seems that I had lower rarity artifact colours included in one part of the capture code but not the other. I should have that fix for next scanner version.

**Comment by yoonbin9300** [comment]
Got it now! Thank you for the clarification.
