### ISSUE TITLE
Feature request: "Read Stats" Hotkey

### ISSUE THREAD

**Issue by jack5mikemotown** [D1firehail/AdeptiScanner-GI#16]
Hey, I love this program, it's great, and manual mode is a nice safety feature but having to click back and forth is quite tedious. I figured a hotkey to read an artifact wouldn't be particularly hard to implement and it would save a lot of clicking back and forth

**Comment by D1firehail** [comment]
IIRC, reading a hotkey while genshin is focused is only possible if the program is running as admin. Manual mode was made without needing to run as admin, but it makes sense to have as a mid-point between current manual and automatic.

I'll look into it when I have the time. No guarantees, but I estimate a new release with it some time during 4.2 or maybe 4.3.

**Comment by D1firehail** [comment]
Added with V2.1.0
