### ISSUE TITLE
Feature Request: Ignore equipped status

### ISSUE THREAD

**Issue by iwantcookiesnow** [D1firehail/AdeptiScanner-GI#18]
I'm often using random characters I don't use as placeholders to hold artifacts for characters I don't yet own, then use an optimizer to switch the artifacts to the intended characters. Unfortunately, each time I scan and import my artifacts, my changes get overwritten and the artifacts are back on the placeholder characters, which is leading to a somewhat annoying loop of switching artifacts around to then have them reset again some time later. 
I am therefore requesting a setting that completely ignores if an artifact is equipped or who has what equipped. I am aware of the setting "Always include equipped" which I uncheck every time, but it's not doing what I'd expect it to do so I assume that I'm misunderstanding its function. 
Thank you.

**Comment by D1firehail** [comment]
"Always include equipped" gives an exception to the export filters. For example, if your filter is set to just level 20 artifacts and your Bennett has an unleveled goblet, the goblet still gets exported.

Should be simple to add, I'll do it for next release.

**Comment by D1firehail** [comment]
Added with V2.1.0
