### ISSUE TITLE
My Box for overlap with eachother

### ISSUE THREAD

**Issue by mowkibowki** [D1firehail/AdeptiScanner-GI#23]
I use v 2.20 

![image](https://github.com/user-attachments/assets/8d8c876c-00ad-4e05-9e6f-f07fd1d7fdbb)

**Comment by D1firehail** [comment]
It's an issue when using a screen scaling (DPI) other than 100%. 
Until it's fixed, I recommend changing that setting to 100% on the relevant screens when using AdeptiScanner.
