### ISSUE TITLE
Scanner no longer working

### ISSUE THREAD

**Issue by R3nierjvr** [D1firehail/AdeptiScanner-GI#3]
Hi I have used this last month and was fine, but sine i tried to day everything comes back as a bad result even if I upload the images directly to Genshin Optimizer it also identifies everything incorrect ????.

Using v1.1 screen res set 1600x900

I have also used other scanner same result, not sure what is happening ?

**Comment by R3nierjvr** [comment]
It scans saves the images but all the values return as nul
![GenshinArtifactImgFiltered 2022-02-02 14-09-3756](https://user-images.githubusercontent.com/26996566/152318067-58b7b55e-553c-45b2-b987-2554bf530c72.png)
![GenshinArtifactImg 2022-02-02 14-13-1671](https://user-images.githubusercontent.com/26996566/152318220-a62116e0-e7e3-43a8-aa55-be2bbabf4a5c.png)

Heres the canned images for one artifact
All the result return as bad and none good

all feathers come back with main stat HP% and should be Atk. and all other that has atk% come back as HP%

**Comment by D1firehail** [comment]
You have some form of sharpening or other image filter going on, which is causing 2 issues
1. The left edge gets pushed a few pixels, which is barely enough to trigger an issue in my detection system. 
2. The colour of the set name gets changed too far for my detection system to pick it up. 

I can probably make both of these areas more lenient so it'd work in the equivalent situation in the future, but as it's a situation already described in the readme I won't make a new release just for this. I'll likely release a new version that includes those adjustments after 2.5 drops.

For clarity, below is a copy of the part of the readme which is relevant to the problem you're having. 

- AdeptiScanner relies on specific colour values ~~and a white window header~~ to identify the contents of the image
    - Anything that changes in-game colours can mess up the results. Examples of programs/features that can interfere is Reshade, Windows Night Light, F.lux, Nvidia Filters and Colourblind compensation tools.
    -   ~~If your window header for the game is not white, try changing it in Windows settings (Themes -> Colours). If that isn't an option, you can try tricking it by covering the window header with a mostly white window like notepad.~~

**Comment by R3nierjvr** [comment]
> You have some form of sharpening or other image filter going on, which is causing 2 issues

You my friend are by far the best, quick response and you nailded it turned out I did have exactly this running

![image](https://user-images.githubusercontent.com/26996566/152406352-e2001bfe-4297-470b-9fd0-a05e2db02369.png)

You solved and for that if I ever run into a bar and your there drinks are on the house :)
