### ISSUE TITLE
level getting read incorrectly?

### ISSUE THREAD

**Issue by huizichin** [D1firehail/AdeptiScanner-GI#4]
![image](https://user-images.githubusercontent.com/16850884/166105329-49296f64-4d3c-4f86-9c08-1ab690718fc3.png)

**Comment by D1firehail** [comment]
The preview image looks a bit more pixelated than usual, what resolution was the game running in?

**Comment by huizichin** [comment]
1280x720

**Comment by D1firehail** [comment]
See point 1 under ["How to prepare for scanning"](https://github.com/D1firehail/AdeptiScanner-GI#how-to-prepare-for-scanning).

I may be able to circumvent the issue by making it rely on the main stat value to get the level, but that would need to be tested properly

**Comment by huizichin** [comment]
well it is the same aspect ratio.
but 720p seem like something a lot of people run genshin on. especially on lower end specs
