### ISSUE TITLE
Vermillion Hereafter

### ISSUE THREAD

**Issue by xSerisuu** [D1firehail/AdeptiScanner-GI#6]
Hi!  Adepti Scanner appears to have an issue with the Vermillion Hereafter set. I've updated to the latest scanner files, but it provides an error and can't read them no matter what.  I've checked and it appears correct in the ArtifactInfo.JSON and I've ensured I downloaded the latest version. The bad results all read "Set: Null-------"

**Comment by xSerisuu** [comment]
![image](https://user-images.githubusercontent.com/113572490/190310578-15d1e4b9-c2d8-46c6-a070-43bb9c6d71a9.png)
I have only moved the scanner on top of the game window to take a screenshot of both.

**Comment by D1firehail** [comment]
Vermillion was briefly removed from the list of 5 star sets, but that was fixed 2 weeks ago. The correct version should have 2 entries for Vermillion, on line 136 for 5 star and line 273 for 4 star. The broken version would have it only on line 272 for 4 star.

**Comment by xSerisuu** [comment]
You're right, thank you!  I must have updated it before it was fixed.  Sorry about that.
