### ISSUE TITLE
Unable to run the program 

### ISSUE THREAD

**Issue by wysit** [D1firehail/AdeptiScanner-GI#7]
When I try to run the program (in administrator mode), I get this error: 
![image](https://user-images.githubusercontent.com/64245115/196215327-e05de25c-0d4d-4c02-820c-c3821877675b.png)

**Comment by D1firehail** [comment]
Does the file path to the folder include any letters that don't appear in the english alphabet?

**Comment by wysit** [comment]
Yes it does, is that what is causing the kitchen?
