### ISSUE TITLE
Scanner could not start

### ISSUE THREAD

**Issue by RuneHeart109** [D1firehail/AdeptiScanner-GI#8]
This appears whenever I try to open the application, what exactly am I missing here?

![image](https://user-images.githubusercontent.com/118785527/203201271-851f8186-4ab4-4118-b8d6-69a4b89e5a59.png)

**Comment by D1firehail** [comment]
I believe that one is caused by not having an appropriate version of Microsoft Visual C++ Redistributable (either x86 and/or x64). [See first section of readme](https://github.com/D1firehail/AdeptiScanner-GI#adeptiscanner-gi)

**Comment by RuneHeart109** [comment]
> I believe that one is caused by not having an appropriate version of Microsoft Visual C++ Redistributable (either x86 and/or x64). [See first section of readme](https://github.com/D1firehail/AdeptiScanner-GI#adeptiscanner-gi)

Oh yep, that was it, thank you. I swear I had both versions installed, must've mistaken it.
